### ISSUE TITLE
How to decrease swipe sensitiveness

### ISSUE THREAD

**Issue by mkiany4** [pwittchen/swipe#17]
Hello, my friend.
I have a problem with this library.
Question: how to decrease sensitiveness of the swipe right event?

**Comment by pwittchen** [comment]
Hi,

Right now, it's not possible because swiping threshold is hardcoded in [`SWIPING_THRESHOLD`](https://github.com/pwittchen/swipe/blob/master/library/src/main/java/com/github/pwittchen/swipe/library/Swipe.java#L31) static value and swiped threshold is hardcoded in [`SWIPED_THRESHOLD`](https://github.com/pwittchen/swipe/blob/master/library/src/main/java/com/github/pwittchen/swipe/library/Swipe.java#L36) static value.

Nevertheless, we can add the possibility to configure these values.

**Comment by pwittchen** [comment]
Documentation is added here: https://github.com/pwittchen/swipe#configuring-swipe-threshold.
This functionality will be available in the next release.
